version: 2
updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"

  # 2. Python packages (using pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "python"
      - "dependencies"
    groups:
      python-dependencies:
        patterns:
          - "*"
