from __future__ import annotations

from typing import Protocol

from .migrations import Versioned
from .models.shared import EntityConfig, EntityConfigV3


class Config(Versioned, Protocol):
    @staticmethod
    def exists() -> bool: ...
    def save(self): ...
    @staticmethod
    def load() -> Config: ...
    def entity(self, name: str) -> EntityConfig | EntityConfigV3 | None: ...
    def set_entity_account(self, name: str, account_id: str): ...
